### ISSUE TITLE
regenerate test data error clarification

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#165]
### Description

When running `npm run dev` I sometimes get this error about the call to regenerate test data failing: 
![image](https://user-images.githubusercontent.com/6308571/184923954-b091dd74-cfa5-4ddd-ab27-d407f074f663.png)

The error is confusing for a couple reasons:
* I'm running in dynamic mode, so I don't think it should be generating test data anyway
* There's no explanation of what actually went wrong, and no additional details in the terminal

### Suggested solution

Either don't show the message at all when test data isn't relevant, or make details about the specific error encountered so that the user can fix it. 

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by nbramblett** [comment]
A few notes from digging in a bit:

- This error should _only_ show in dynamic mode, because when running Dynamic Mode the server calls `generate-test-data at startup in order to guarantee a fresh and accurate set of entities for the index.
- It looks like this error occurs when you have a nonzero exit code, but we're not writing to stdout, so you can't see what the actual output of generate-test-data is.

I think the best way to improve visibility is to capture the output of the generate command and surface it iff the exit code is nonzero. I can work on updating this - shouldn't be too hard.

**Comment by lambdaFun94** [comment]
Revisiting this. Dynamic mode is now the default and I frequently encounter this error when there is nothing wrong. Can we just remove this message since  in every case I have seen, it has been a red herring?

**Comment by mkilpatrick** [comment]
This error has been removed altogether.
