### ISSUE TITLE
Can't use fields that contain HTML Tags

### ISSUE THREAD

**Issue by PaigePonzeka** [yext/pages#225]
### Describe the bug

I have a custom field `c_HTMLSnippet` that we use to power HTML Widgets (think Tableau dashboards and iFrames) but I'm having issues with the HTML Rendering loading the template as soon as I add `c_HTMLSnippet` to the stream. 

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 40.80 MB / 16.00 GB
    Shell: 5.0.16 - /usr/local/bin/bash
  Binaries:
    Node: 17.0.0 - ~/.nvm/versions/node/v17.0.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 103.0.2
    Safari: 15.6.1
  npmPackages:
    @yext/pages: ^1.0.0-beta.1 => 1.0.0-beta.6
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by bhainesva** [comment]
Going to reopen b/c I was able to reproduce this on beta.13 by trying to add a script tag to a multiline text field. The description of how to render the html from a field using `dangerouslySetInnerHTML` makes sense but the page seems to break just by including the field in the stream before even trying to use it.

The problem is that html isn't escaped when injected into the page as the `__INITIAL__DATA__` variable. The `encodeURI` call in Paige's repo was a workaround to avoid this issue by escaping the HTML content manually. 

There are some more details in this thread: https://yext.slack.com/archives/C02UVSE7P6W/p1663707616678049?thread_ts=1663706042.859789&cid=C02UVSE7P6W.
