### ISSUE TITLE
Static pages are downloaded as files instead of rendered. 

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#240]
### Describe the bug

Clone and serve this commit: https://github.com/big-ol-sandbox/Interviews/tree/bug. 

Runt `yarn dev` and go to http://localhost:5173/static. This will trigger a download of the content of the static page. 

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/6308571/194684270-0799e87d-11bd-4e51-881d-e0830f9a950f.png">

Downgrading from  `    "@yext/pages": "1.0.0-beta.7",` to `    "@yext/pages": "1.0.0-beta.6",` fixes it. 

### Reproduction

https://github.com/big-ol-sandbox/Interviews/tree/bug

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 273.03 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.7 => 1.0.0-beta.7
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
This is because the contentType is dynamically interpreted based on `getPath`. In this case the function returns `static/${Math.random().toString()}` which results in something like _static/0.976972907181533_. The function itself looks for a `.` and gets the last part after it. This leads to a content type of 976972907181533, which is obviously wrong and apparently the browser just interprets that as a file.

I'll put up a PR that correctly interprets the path using valid mime-types instead of the naive check it's doing now. In the meantime, if you just change your `getPath` to return _static_ or _static.html_ that will solve your problem.

**Comment by mkilpatrick** [comment]
Fixed in https://github.com/yext/pages/commit/4c25b93a46707913da456fdaa8908910580a22c4
