### ISSUE TITLE
Map Pin Clustering

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#279]
### Description

A feature that we are sometimes asked to implement is Pin Clustering. 

You can see an example here on Aldi's locator: https://stores.aldi.us/stores?r=31&l=en&q=illinois. 

When zoomed out locations are grouped together into a single pin:
![image](https://user-images.githubusercontent.com/6308571/207641306-ce4297a9-2724-4c2b-837d-5e5b8230f48b.png)

Clicking on one of those clusters zooms in and splits out the individual locations into separate pins:
![image](https://user-images.githubusercontent.com/6308571/207641460-19af1140-6be5-4a38-b8de-64da9f3ed77a.png)

### Suggested solution

I don't have a suggested implementation. This is a very rough draft we came up with at some point: https://github.com/Jared-Hood/react-maps-component/compare/clusterer?expand=1. 

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by tatimblin** [comment]
Heads up that there might not be much discussion here for this, because of the process to move react components to [their own repo](https://github.com/yext/react-components). I don't think we want (certainly aren't monitoring) issues on the repo yet.
Think it's fine to let it exist here until an item gets made or further discussion happens, just calling that migration out
